on:
  push:
    branches:
      - main
    paths:
      - "cv/**"
      - ".github/workflows/release-gh-pages.yml"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare file structure
        run: |
          mv ./cv/cv.html ./cv/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cv
          publish_branch: gh-pages
